name: Daily Commit

on:
  schedule:
    - cron: '0 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

permissions:
  contents: write  # Grants write permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Manual commit on $(date)" >> README_new.md
          git config user.name 'anupamk36'
          git config user.email 'anupamk36@live.com'
          git add .
          git commit -m "Manual commit"
          git push origin HEAD:main
